# Introduction

Rapid legalization of gambling across the United States and the rise of app-based and online betting platforms has propelled sports betting into a multi-billion-dollar industry. This transformation has introduced new forms of entertainment, economic opportunity, and media attention for athletes, but it has also sparked critical questions about who participates in this growing industry and why. Specifically, how are patterns of sports betting participation distributed across socioeconomic groups? The new age of sports betting has introduced additional gambling risks. Because of these reasons, we seek to answer: How do the socioeconomic factors: education and income, correlate with sports betting handle at the state level? 

Our hypothesis is that groups of lower socioeconomic status, with particular regards to income and education, would see higher rates of sports betting participation. Historically, gambling in general has been associated with lower-income and less-educated households. However, with sports betting being such a new venture in the gambling world, it is not widely associated with these socioeconomic trends yet. However, if these groups are in fact participating at a higher rate than others of higher socioeconomic standing, it raises concerns. For many individuals, gambling may reflect not recreational entertainment, but economic desperation, misinformed optimism, or a perceived path to financial mobility. In such contexts, the consequences of betting can deepen cycles of financial instability. At the same time, education levels may influence individuals' understanding of risk, probability, and long-term outcomes, potentially creating an equity gap in financial decision-making and loss aversion. 
